var repList = const [
  {'type' : '와이퍼',
   'name' : '보쉬 클리어핏 와이퍼',
   'price' : '19700',
   'image' : 'image/wiper.jpg'},
  {'type' : '와이퍼',
   'name': '카렉스 레인스톰 하이브리드 와이퍼',
   'price' : '19700',
   'image' : 'image/wiper.jpg'},
  {'type' : '워셔액',
   'name': '한눈알 에탄올 워셔액',
   'price' : '10000',
   'image' : 'image/washer.jpeg'},
  {'type' : '워셔액',
   'name': '파이널 프리미엄 에탄올 워셔액',
   'price' : '10000',
   'image' : 'image/wiper.jpg'},
  {'type' : '엔진오일',
   'name': 'SK 루브리컨츠 지크탑',
   'price' : '10000',
   'image' : 'image/wiper.jpg'},
  {'type' : '엔진오일',
   'name': '엔진오일 갈자',
   'price' : '10000',
   'image' : 'image/wiper.jpg'},
  {'type' : '배터리',
   'name': '피카츄 백만볼트',
   'price' : '10000',
   'image' : 'image/wiper.jpg'},
  {'type' : '배터리',
   'name': '배고파 밥줘',
   'price' : '10000',
   'image' : 'image/wiper.jpg'},
];